version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
            sudo apt install -y curl
            curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt install -y nodejs
            sudo apt install build-essential
            node -v
      - run: cd ./seccom-cctv-docs && yarn install --ignore-engines && yarn run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    machine:
        image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: aws s3 sync ./seccom-cctv-docs/build s3://es-01-docusaurus
    

workflows:
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
